[package]
name = "wasm"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
blsful = { version = "2.5.7", default-features = false, features = ["rust"] }
base64_light = "0.1"
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4"
hd-keys-curves-wasm = { version = "0.1", default-features = false, features = ["k256", "p256"], git = "https://github.com/LIT-Protocol/hd-keys-curves-wasm.git" }
serde = "1.0"
serde_json = "1.0"
serde_bare = "0.5"
serde-wasm-bindgen = "0.6"

elliptic-curve = "0.13"
k256 = { version = "0.13", features = ["arithmetic"] }
p256 = { version = "0.13", features = ["arithmetic"] }
sha2 = "0.10"

wee_alloc = { version = "0.4.5", optional = true }

console_error_panic_hook = { version = "0.1.7", optional = true }
wasm-bindgen-futures = "0.4.40"
js-sys = "0.3.67"

sev = { version = "2.0.2", default-features = false, features = [
  "snp",
  "crypto_nossl",
] }
rand = "0.8"
serde_bytes = "0.11.14"
tsify = { version = "0.4.5", default-features = false, features = ["js"] }
jubjub = { version = "0.10.4", git = "https://github.com/LIT-Protocol/jubjub.git", branch = "main"}


[dev-dependencies]
wasm-bindgen-test = "0.3.34"
ciborium = "0.2"
k256 = "0.13"
rand = "0.8"
rand_chacha = "0.3"
digest = "0.10"

[profile.release]
opt-level = "z"
lto = true
wasm-opt=['-Os']

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = ['-g', '-O']