config:
  target: 'dummy'
  phases:
    # Over 60s, ramp up to creating 70 vusers per second
    - duration: 60
      arrivalRate: 5
      rampTo: 70
      name: 'Ramp Up'
    # Over 300s, sustain 70 vusers per second
    - duration: 300
      arrivalRate: 70
      name: 'Sustained Encrypt & Decrypt'
    # Over 60s, ramp down to creating 20 vusers per second
    - duration: 60
      arrivalRate: 20
      name: 'Ramp Down'
  processor: '../src/processors/multi-endpoints.ts'

scenarios:
  - name: 'Encrypt & Decrypt Stress Test'
    weight: 100
    flow:
      - function: 'runEncryptDecryptTest'
      - think: 0.1
