config:
  target: 'dummy'
  phases:
    # Over 60s, ramp up to creating 30 vusers per second
    - duration: 60
      arrivalRate: 5
      rampTo: 30
      name: 'Ramp Up'
    # Over 3600s, sustain 30 vusers per second
    - duration: 3600
      arrivalRate: 30
      name: 'Sustained PKP Signing (Soak)'
    # Over 60s, ramp down to creating 20 vusers per second
    - duration: 60
      arrivalRate: 20
      name: 'Ramp Down'
  processor: '../src/processors/multi-endpoints.ts'

scenarios:
  - name: 'PKP Sign Stress Test'
    weight: 100
    flow:
      - function: 'runPkpSignTest'
      - think: 0.1
